services:
  opensearch:
    image: "opensearchproject/opensearch:latest"
    ports:
      - 9200:9200
      - 9600:9600
    restart: on-failure
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g"
      - DISABLE_SECURITY_PLUGIN=true
    healthcheck:
        test: curl --fail http://localhost:9200/_cat/health -ku 'admin:admin' || exit 1
        interval: 10s
        timeout: 1s
        retries: 10
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
