# To allow your IDE to autocomplete and validate your YAML pipelines, name them as <name of your choice>.haystack-pipeline.yml

version: ignore

components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: OpenSearchDocumentStore
    params:
      host: localhost
  - name: Retriever
    type: BM25Retriever
    params:
      document_store: DocumentStore    # params can reference other components defined in the YAML
      top_k: 100
  - name: JsonFileConverter
    type: JsonConverter

pipelines:
  - name: query    # a sample extractive-qa Pipeline
    nodes:
      - name: Retriever
        inputs: [Query]
  - name: indexing
    nodes:
      - name: JsonFileConverter
        inputs: [File]
      - name: Retriever
        inputs: [JsonFileConverter]
      - name: DocumentStore
        inputs: [Retriever]
